import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/header";
import Title from "./components/title";
import Typewriter from "./components/title";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      {/* <header className="bg-red-300 flex">sdads</header> */}
      <body className={inter.className}>
        <Nav/>
        {children}

        {/* <Typewriter text='jsajdjasdj'  delay= {100} /> */}


        </body>
    </html>
  );
}
